### ISSUE TITLE
[ENHANCEMENT] Add support for custom model data in the tier generator

### ISSUE THREAD

**Issue by goflishMC** [MythicDrops/MythicDrops#637]
This would add support for custom model data in the tier generator so we can give custom textures to the random items.

## Detailed Description

This is an example of what I'm talking about: https://i.imgur.com/R0MMEXV.jpeg

## Context

This would allow anyone to add custom model data for the random items and give more value to MythicDrops

**Comment by zorkenlide** [comment]
This is EXACTLY what I was discussing with my team the other day.

Support for randomly generated custom model data according to different groups and base item types. So you could have three different custom models for LEGENDARY netherite_sword and other custom models for EPIC netherite_sword.

This would be so amazing for our RPG server and I will gladly contribute for development of this feature!

**Comment by zorkenlide** [comment]
It could also work like this:
custom-model-data:
  - 10
  - 11
  - 12
    special:
    - diamond sword:
      - 14 5 #the second number is weight - chance for the diamond sword to get custom_model_data: 14
      - 15 7
      
You could have several different custom-model-data skins for items this way and some of them could be more rare.

**Comment by rysato1** [comment]
As Zork already wrote, we would really like it if a custom model could be assigned to a custom sword using ItemAdder, which we also have on the server. It tells us the IDs of individual items and we would like to pair them with mythicdrops custom armor and swords.

We really like what he suggests.

"It could also work like this:
custom-model-data:


10
11
12
special:
    diamond sword:
        14 5 #the second number is weight - chance for the diamond sword to get custom_model_data: 14
        15 7

You could have several different custom-model-data skins for items this way and some of them could be more rare."

**Comment by StOsCZ** [comment]
That sounds really amazing guys. In using itemsadder too, never realized it could ve used like this with mythic drops.
Would really appreciate it too. 
Im doing it manually so far.

**Comment by SmrdutyOrangutan** [comment]
Another ItemsAdder user here, and I’d kill for this. We’ve implemented a lot of workarounds to give our players custom models and this would essentially cut off the middleman and would make world bosses more rewarding – it just feels more natural to get Named Equipment from a boss directly.
And as someone above me suggested – different rarities for skins would bring this to next level.

**Comment by ToppleTheNun** [comment]
The way that this would need to be written from the config side would be more akin to:
```yaml
custom-model-data:
  - 10
  - 11
  - 12
material-custom-model-data:
  diamond_sword:
    - model_data: 14
      weight: 5
    - model_data: 15
      weight: 7
```

This would be a whole new addition to tier generation so it should be fairly straightforward to implement, but it will come after I'm done with the work for #687.

**Comment by ToppleTheNun** [comment]
This has been merged into the main branch and is available for testing in 8.4.0, which will become available as a GitHub release shortly.

**Comment by zorkenlide** [comment]
I am so sorry, I would like to test it but I have not found a way to download the .jar from Github. Do I have to compile it by myself somehow? :)

Thanks, keep up the great work

**Comment by ToppleTheNun** [comment]
Only the ZIPs are currently uploaded to the releases, you can grab it from here:

![Screenshot 2023-01-23 102138](https://user-images.githubusercontent.com/1672786/214077696-087e9ba8-05d6-4438-845d-9139ce410f06.png)

**Comment by zorkenlide** [comment]
I am not sure it works for me, even when I set these settings to epic tier:
```
custom-model-data:
  - model-data: 10000
    weight: 1
```

and then reload, none of the generated epic IRON_SWORDS (/md give tier NICK epic 30) has any custom-model-data.

Has anyone else succesfully tested this? It is possible I am doing something wrong.

**Comment by ToppleTheNun** [comment]
I'll double check the implementation and test on my end.

**Comment by ToppleTheNun** [comment]
I figured out the cause, it's a bit weird but I'll get a fix in shortly.

**Comment by zorkenlide** [comment]
I can confirm, it works now. Amazing!
Thank you for your fast implementation and support.

**Comment by zorkenlide** [comment]
I am not sure if the material detection works right.
I have this configuration: there is only one custom-model-data ID for DIAMOND_HOE, for example, but when I generate 30 items from the same tier, it generates a lot of DIAMOND_HOEs with different custom-model-data IDs.

As if there was no "material" requirement.

```
custom-model-data:
  - model-data: 10001
    weight: 1
    material: WOODEN_PICKAXE
  - model-data: 10001
    weight: 1
    material: WOODEN_HOE
  - model-data: 10001
    weight: 1
    material: WOODEN_AXE
  - model-data: 10001
    weight: 1
    material: WOODEN_SHOVEL
  - model-data: 10000
    weight: 1
    material: STONE_PICKAXE
  - model-data: 10000
    weight: 1
    material: STONE_HOE
  - model-data: 10000
    weight: 1
    material: STONE_AXE
  - model-data: 10000
    weight: 1
    material: STONE_SHOVEL
  - model-data: 10000
    weight: 1
    material: IRON_PICKAXE
  - model-data: 10000
    weight: 1
    material: IRON_HOE
  - model-data: 10000
    weight: 1
    material: IRON_AXE
  - model-data: 10000
    weight: 1
    material: IRON_SHOVEL
  - model-data: 10000
    weight: 1
    material: GOLD_PICKAXE
  - model-data: 10000
    weight: 1
    material: GOLD_HOE
  - model-data: 10000
    weight: 1
    material: GOLD_AXE
  - model-data: 10000
    weight: 1
    material: GOLD_SHOVEL
  - model-data: 10000
    weight: 1
    material: DIAMOND_PICKAXE
  - model-data: 10001
    weight: 1
    material: DIAMOND_HOE
  - model-data: 10001
    weight: 1
    material: DIAMOND_AXE
  - model-data: 10001
    weight: 1
    material: DIAMOND_SHOVEL
  - model-data: 10001
    weight: 1
    material: NETHERITE_PICKAXE
  - model-data: 10000
    weight: 1
    material: NETHERITE_HOE
  - model-data: 10000
    weight: 1
    material: NETHERITE_AXE
  - model-data: 10000
    weight: 1
    material: NETHERITE_SHOVEL
```

And this even assigned custom-data-model IDs for swords, which are not even in the config, for example. So I am not sure that the "material: Optional field to make this custom model data only go on items with this material." works properly.
